#ifndef __RT_AI_HAND_MODEL_H
#define __RT_AI_HAND_MODEL_H

#include <hand.h>
#include <hand_data.h>

/* model info ... */

// model name
#define RT_AI_HAND_MODEL_NAME			"hand"
#define RT_AI_HAND_WORK_BUFFER_BYTES		AI_HAND_DATA_ACTIVATIONS_SIZE
#define RT_AI_HAND_DATA_WEIGHTS_SIZE		AI_HAND_DATA_WEIGHTS_SIZE

#define RT_AI_HAND_BUFFER_ALIGNMENT		AI_HAND_ACTIVATIONS_ALIGNMENT

#define RT_AI_HAND_IN_NUM				AI_HAND_IN_NUM
#define RT_AI_HAND_IN_1_SIZE				AI_HAND_IN_1_SIZE
#define RT_AI_HAND_IN_1_SIZE_BYTES		AI_HAND_IN_1_SIZE_BYTES
#define RT_AI_HAND_IN_TOTAL_SIZE_BYTES	(AI_HAND_IN_1_SIZE_BYTES)
#define RT_AI_HAND_IN_SIZE_BYTES			{AI_HAND_IN_1_SIZE_BYTES}


#define RT_AI_HAND_OUT_NUM				AI_HAND_OUT_NUM
#define RT_AI_HAND_OUT_1_SIZE			AI_HAND_OUT_1_SIZE
#define RT_AI_HAND_OUT_1_SIZE_BYTES		AI_HAND_OUT_1_SIZE_BYTES
#define RT_AI_HAND_OUT_TOTAL_SIZE_BYTES	(AI_HAND_OUT_1_SIZE_BYTES)
#define RT_AI_HAND_OUT_SIZE_BYTES		{AI_HAND_OUT_1_SIZE_BYTES}


#define RT_AI_HAND_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
